openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/TECHSCRIPSI/OmniCart/1.0.0'
info:
  version: 1.0.0
  title: OmniCart API
  description: OmniCart Payment Gateway
  contact:
    name: ''
paths:
  /payment:
    post:
      summary: Payment Creation
      description: Use this method to send a payment request to OmniCart.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  format: int32
                  description: 'Payment amount in minimum currency units.'
                  example: '599'
                amountModifier:
                  type: number
                  format: float
                  description: 'The <code>amount</code> parameter is multiplied by this value. You can use it to apply quantities or discounts.'
                  example: '0.9'
                currency:
                  type: string
                  description: '<a href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a> currency code.'
                  example: 'EUR'
                description:
                  type: string
                  description: 'Optional description.'
                  example: 'Online order.'
                language:
                  type: string
                  description: '<a href="https://localizely.com/iso-639-1-list/">ISO 639-1</a> language code.'
                  example: 'en'
                toConfirm:
                  type: boolean
                  description: 'Is it a two-step payment:<ul><li><code>true</code> — payment confirmation required;</li><li><code>false</code> — confirmation not required.</li></ul>'
                  example: true
                confirm:
                  type: object
                  properties:
                    auto:
                      type: string
                      description: 'Defines an auto action that is taken after the specified period passes:<br /><ul><li><code>complete</code> — the payment is completed automatically after the specified period;</li><li><code>exipre</code> — the payment expires automatically after the specified period.</li></ul>'
                      enum: [complete, expire]
                      example: 'complete'
                    period:
                      type: string
                      description: 'Time period after which the action set in <code>auto</code> (<code>complete</code> or <code>expire</code>) is taken.'
                      enum: [minutes, hours, days]
                      example: 'hours'
                    value:
                      type: integer
                      description: 'Number of minutes, hours, or days after which the action set in <code>auto</code> (<code>complete</code> or <code>expire</code>) is taken.'
                      example: '12'
              required:
                - amount
                - currency
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    code: OK
                    message: null
                    timestamp: '2023-08-11T13:31:17.580+03:00'
                required:
                  - code
                  - timestamp