openapi: 3.1.0
info:
  title: OmniCart API
  version: 1.0.0
  description: API description.
components:
  schemas:
    tag:
      type: string
      description: your tag
    amount:
      type: integer
      title: " "
      format: int32
      examples:
        - 5998
      description: Payment amount in minimum currency units.
    currency:
      type: string
      title: " "
      examples:
        - EUR
      description: "[ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code."
    language:
      type: string
      title: " "
      examples:
        - en
      description: "[ISO 639-1](https://localizely.com/iso-639-1-list/) language code."
    toConfirm:
      type: boolean
      title: " "
      description: 2-step payment
    confirmAuto:
      enum:
        - expire
        - complete
      type: string
      title: " "
      examples:
        - expire
      description: "20250114070859"
    confirmValue:
      type: integer
      title: " "
      format: int32
      description: "20250114070902"
    confirmPeriod:
      enum:
        - minutes
        - hours
        - days
        - weeks
      type: string
      title: " "
      examples:
        - days
      description: "20250114070900"
    amountModifier:
      type: number
      title: " "
      format: float
      examples:
        - 0.9
      description: "`amount` parameter is multiplied by this value. You can use it to
        calculate quantities or discounts.'"
      minimum: 0.01
    subscriptionValue:
      type: integer
      title: " "
      format: int32
      examples:
        - 1
      description: "20250114070923"
    subscriptionPeriod:
      enum:
        - minutes
        - hours
        - days
        - weeks
        - months
        - years
      type: string
      title: " "
      examples:
        - months
      description: "20250114070925"
    confirm:
      type: object
      title: " "
      properties:
        auto:
          $ref: "#/components/schemas/confirmAuto"
        period:
          $ref: "#/components/schemas/confirmPeriod"
        value:
          $ref: "#/components/schemas/confirmValue"
      required:
        - auto
        - period
        - value
      description: Блок подтверждения платежа
    timerPeriod:
      type: string
      title: " "
      description: set period
      exampls:
        - days
      default: months
      enum:
        - minutes
        - hours
        - days
        - weeks
        - months
        - years
    timerValue:
      type: number
      title: " "
      examples:
        - 2
      description: ""
    timerRepeat:
      type: boolean
      title: " "
      description: Whether to repeat purchase
    productId:
      type: string
      title: " "
      description: Product identifier.
    timer:
      type: object
      title: " "
      properties:
        period:
          $ref: "#/components/schemas/timerPeriod"
        value:
          $ref: "#/components/schemas/timerValue"
        repeat:
          $ref: "#/components/schemas/timerRepeat"
      required:
        - period
        - value
        - repeat
      description: set timer
    setTimer:
      type: boolean
      title: " "
      description: set timer for order
    quantity:
      type: number
      minimum: 0.01
      format: float
      examples:
        - 1
      description: "quantity of product"
    amoutModifier:
      type: number
      minimum: 0.01
      format: float
      description: "multiply by this value"
    item:
      type: object
      properties:
        amount:
          $ref: "#/components/schemas/amount"
        productId:
          $ref: "#/components/schemas/productId"
        quantity:
          $ref: "#/components/schemas/quantity"
        toConfirm:
          $ref: "#/components/schemas/toConfirm"
        confirm:
          $ref: "#/components/schemas/confirm"
        setTimer:
          $ref: "#/components/schemas/setTimer"
        timer:
          $ref: "#/components/schemas/timer"
        tag:
          $ref: "#/components/schemas/tag"
        amountModifier:
          $ref: "#/components/schemas/amountModifier"
      required:
        - amount
        - productId
        - quantity
        - toConfirm
        - confirm
        - setTimer
        - timer
        - tag
        - amountModifier
      description: product item
    cart:
      type: array
      items:
        $ref: "#/components/schemas/item"
      description: list of product
    direct:
      type: boolean
      description: direct payment
  responses:
    Ok:
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
      description: The request was successful, and the server has returned the
        requested resource in the response body.
paths:
  /cart:
    post:
      summary: make payment
      operationId: makePayment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  $ref: "#/components/schemas/language"
                currency:
                  $ref: "#/components/schemas/currency"
                direct:
                  $ref: "#/components/schemas/direct"
                toConfirm:
                  $ref: "#/components/schemas/toConfirm"
                confirm:
                  $ref: "#/components/schemas/confirm"
                setTimer:
                  $ref: "#/components/schemas/setTimer"
                timer:
                  $ref: "#/components/schemas/timer"
                cart:
                  $ref: "#/components/schemas/cart"
      responses:
        "200":
          $ref: "#/components/responses/Ok"
