import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  start: [{type: 'autogenerated', dirName: 'integration'}],
  api: [{type: 'autogenerated', dirName: 'api'}],
  panel: [{type: 'autogenerated', dirName: 'panel'}],
  scenarios: [{type: 'autogenerated', dirName: 'scenarios'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;